title: Blueshores
description: Living foreshores for working ports
baseurl: "/Blueshores"
url: "https://blueshoresweb.github.io"

theme: minima
markdown: kramdown

header_pages:
  - index.md
  - objectives.md
  - case-studies/index.md
  - partners.md
  - publications.md
  - news/index.md
  - about.md

# GitHub Pages configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap